# Generated by Django 5.2.1 on 2025-05-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_created_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
