# Generated by Django 5.2.1 on 2025-08-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('total_cost', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Заказ создан', '1'), ('В работе', '2'), ('Завершен', '3')], default='Заказ создан')),
                ('cart', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basket.cartanduser')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
    ]
