# Generated by Django 5.2.1 on 2025-08-22 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_cartanduser_cartandproduct_delete_cart'),
        ('orders', '0002_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basket.cartanduser'),
        ),
    ]
