# Generated by Django 5.2.1 on 2025-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Заказ создан'), ('2', 'В работе'), ('3', 'Завершен')], default='1', max_length=2),
        ),
    ]
