# Generated by Django 5.2.1 on 2025-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Заказ создан', '1'), ('В работе', '2'), ('Завершен', '3')], default='Заказ создан'),
        ),
    ]
