# Generated by Django 5.2.1 on 2025-08-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CartAndUser',
                'verbose_name_plural': 'CartsAndeUsers',
                'db_table': 'cart_and_user',
            },
        ),
        migrations.CreateModel(
            name='CartAndProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'CartAndProduct',
                'verbose_name_plural': 'CartsAndProducts',
                'db_table': 'cart_and_product',
            },
        ),
    ]
