# Generated by Django 5.2.1 on 2025-08-22 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_initial'),
        ('products', '0008_stockbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CartAndUser',
                'verbose_name_plural': 'CartsAndeUsers',
                'db_table': 'cart_and_user',
            },
        ),
        migrations.CreateModel(
            name='CartAndProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.cartanduser')),
            ],
            options={
                'verbose_name': 'CartAndProduct',
                'verbose_name_plural': 'CartsAndProducts',
                'db_table': 'cart_and_product',
            },
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
